name:                GregLang
version:             0.1.0.0
github:              "Gregory1234/GregLang"
license:             GPL-3.0-only
author:              "Gregory1234"
maintainer:          "Gregory1234@users.noreply.github.com"
copyright:           "2019 Gregory1234"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Gregory1234/GregLang#readme>

dependencies:
  - base >= 4.12 && < 5
  - optparse-applicative >= 0.15 && < 0.16
  - megaparsec >= 8 && < 9
  - containers >= 0.6 && < 1
  - utility-ht >= 0.0.15 && < 0.1
  - split >= 0.2.3.1 && < 0.3
  - transformers >= 0.5.6 && < 0.6
  - lens >= 4.18 && < 5
  - mtl >= 2.2.2 && < 3

library:
  source-dirs: src
  ghc-options:
    - -Wredundant-constraints
    - -Widentities
    - -Wmissing-export-lists
    - -Wall
    - -O2

executables:
  GregLangCompiler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - GregLang

tests:
  GregLang-test:
    main:                MainTest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - GregLang
      - tasty
      - QuickCheck
      - tasty-quickcheck
      - HUnit
      - tasty-hunit
